server:
  port: 9081

spring:
  main:
    banner-mode: off
  r2dbc:
    url: r2dbc:h2:mem:///~mydb;DB_CLOSE_DELAY=-1
    username: sa
    password: password
    pool:
      enabled: true
      max-size: 20
      validation-query: SELECT 1
      initial-size: 5
  data:
    r2dbc:
      repositories:
        enabled: true
  sql:
    init:
      platform: h2
      mode: always
      schema-locations: classpath:db/schema.sql
## { h2-console
  datasource:
    url: jdbc:h2:mem:~mydb;DB_CLOSE_DELAY=-1
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
## } h2-console
