server:
  port: 9081

spring:
  profiles:
    active: dev
  main:
    banner-mode: off
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate.default_schema: APP_TABLES
  sql:
    init:
      schema-locations: classpath:db/schema.sql
      mode: always
logging:
  level:
    org: warn
    com: warn
    ru:
      vk:
        competition:
          minbenchmark:
            controller:
              TableManagerController: warn
              TableManagerService: warn
              TableManagerDao: warn
              TableQueryController: warn
              TableQueryService: warn
              SingleQueryController: warn
              SingleQueryService: warn
              ReportController: warn
              ReportService: warn
